#!/usr/bin/env node
/* ============================================================================
 * tools/build.js — inlines the whole application into single files.
 *
 *   dist/index.html     standalone page; opens from the filesystem, no server
 *   dist/artifact.html  body-content only, for publishing as a Claude Artifact
 *
 * No bundler, no transpiler: the sources are already plain ES5-compatible
 * scripts loaded in dependency order, so "building" means concatenating them
 * in exactly the order index.html declares.
 * ==========================================================================*/
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

function read(rel) { return fs.readFileSync(path.join(ROOT, rel), 'utf8'); }
function exists(rel) { return fs.existsSync(path.join(ROOT, rel)); }

/* Guard against a source file accidentally closing the inline script block. */
function safeJs(src) { return src.replace(/<\/script>/gi, '<\\/script>'); }

let out = html;

/* stylesheets — local files are inlined; remote font links are left alone
 * (fonts.googleapis.com is on the Artifact CSP allowlist, and the CSS declares
 * real fallback stacks so the page renders correctly with no network at all). */
out = out.replace(/<link rel="stylesheet" href="([^"]+)">/g, (m, href) =>
  /^https?:/.test(href) ? m : '<style>\n' + read(href) + '\n</style>');

/* scripts, in declared order */
out = out.replace(/<script src="([^"]+)"><\/script>/g, (m, src) => {
  /* observed.js is generated by the ingest and may legitimately not exist */
  if (!exists(src)) return '<!-- ' + src + ' not present at build time -->';
  return '<script>\n/* ==== ' + src + ' ==== */\n' + safeJs(read(src)) + '\n</script>';
});

fs.mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'dist/index.html'), out);

/* ---- artifact variant: content only, no document scaffolding -------------- */
const title = (out.match(/<title>([\s\S]*?)<\/title>/) || [])[1] || 'LCDOS Terminal';
const head = out.slice(out.indexOf('<head>') + 6, out.indexOf('</head>'));
const body = out.slice(out.indexOf('<body>') + 6, out.lastIndexOf('</body>'));
const styles = (head.match(/<style>[\s\S]*?<\/style>/g) || []).join('\n');
const fontLinks = (head.match(/<link [^>]*fonts\.(googleapis|gstatic)\.com[^>]*>/g) || []).join('\n');

/* Artifact variant: no <!doctype>, <html>, <head> or <body> — the publisher
 * supplies those. Body content goes in unwrapped so #app's 100vh layout still
 * resolves against the document body. */
const artifact =
  '<title>' + title + '</title>\n' +
  fontLinks + '\n' +
  styles + '\n' +
  body.trim() + '\n';

fs.writeFileSync(path.join(ROOT, 'dist/artifact.html'), artifact);

const kb = (n) => (n / 1024).toFixed(0) + ' KB';
console.log('dist/index.html    ' + kb(Buffer.byteLength(out)));
console.log('dist/artifact.html ' + kb(Buffer.byteLength(artifact)));
